version: "3"

services:
  projectname-nuxt:
#    build: .
    image: localhub.etod.me/projectname:latest
    restart: unless-stopped
    networks:
      - app-network-projectname

  nginx:
    image: localhub.etod.me/nginx:latest
    restart: unless-stopped
    networks:
      - app-network-projectname
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - projectname-nuxt

networks:
  app-network-projectname:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.71.0/24
